version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.web
    restart: on-failure:3
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 3s
      timeout: 3s
      retries: 2
      start_period: 5s
    networks:
      - caddy
    deploy:
      replicas: 3
  proxy:
    build:
      context: ./docker/proxy
      dockerfile: Dockerfile.proxy
    depends_on:
      web:
        condition: service_healthy
        restart: true
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  caddy:
