name: Deploy to server
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'src/**'
      - 'docker/**'
      - 'docker-compose.yml'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          script: |
            cd /app/projects/cloud-resume
            git pull
            cp cloud-resume.sh /etc/init.d/cloud-resume
            docker compose -f docker-compose.dev.yml -f docker-compose.yml up --build -d
